import { swPolicy } from '@/lib/offline';

/**
 * The service worker, served from the origin root so its scope is the whole app.
 *
 * A route rather than a file in `public/`, for one reason: the policy is
 * defined once in `src/lib/offline.ts`, tested there by Vitest, and injected
 * here as JSON. A hand-written `public/sw.js` would be a second copy of the
 * rules about what may be cached, and the two would drift — which for a service
 * worker means the tested rules and the shipped rules disagree about whether
 * somebody's page HTML is kept.
 *
 * What is below is mechanism only. Every decision it makes comes from `POLICY`
 * or from `swDecision`'s shape, and there is no rule expressed here that is not
 * expressed there.
 *
 * `Service-Worker-Allowed: /` is belt and braces — a worker served from `/sw.js`
 * already gets the root scope — and the `no-store` on the script itself is what
 * lets a new version replace an old one promptly rather than whenever an
 * intermediary decides to let go of it.
 */

export const dynamic = 'force-static';

function source(): string {
  const policy = swPolicy();

  return `// Generated by src/app/sw.js/route.ts. Do not edit — edit src/lib/offline.ts.
'use strict';

var POLICY = ${JSON.stringify(policy, null, 2)};

// Install: fetch the shell and take it. \`skipWaiting\` is deliberate — a
// household organiser is not an app somebody keeps two tabs of, and a worker
// that waits for every tab to close is a worker that never updates.
self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(POLICY.version).then(function (cache) {
      // { cache: 'reload' } so installing never picks the shell up out of the
      // HTTP cache — an update that installed the previous version's offline
      // page would be worse than not updating.
      return Promise.all(
        POLICY.precache.map(function (url) {
          return cache.add(new Request(url, { cache: 'reload' })).catch(function () {
            // One unreachable shell URL must not fail the whole install and
            // leave the app with no worker at all.
          });
        })
      );
    }).then(function () { return self.skipWaiting(); })
  );
});

// Activate: drop every cache that is not this version, then take over open
// pages. This is how a stale shell is thrown away, and it is the reason
// CACHE_VERSION exists.
self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.map(function (key) {
          return key === POLICY.version ? null : caches.delete(key);
        })
      );
    }).then(function () { return self.clients.claim(); })
  );
});

// The escape hatch. A page can ask this worker to stand down and take its
// caches with it — see the unregister control on /settings. A service worker
// with no way out is the classic way to ship an app that cannot be fixed.
self.addEventListener('message', function (event) {
  if (!event.data || event.data.type !== 'orbit-unregister') return;
  event.waitUntil(
    caches.keys()
      .then(function (keys) { return Promise.all(keys.map(function (k) { return caches.delete(k); })); })
      .then(function () { return self.registration.unregister(); })
      .then(function () { return self.clients.matchAll(); })
      .then(function (clients) {
        clients.forEach(function (c) { c.postMessage({ type: 'orbit-unregistered' }); });
      })
  );
});

/**
 * Mirrors swDecision() in src/lib/offline.ts, which is where it is tested.
 * Anything without a specific reason to be cached is network-only, so a request
 * shape nobody considered behaves as if no worker were installed at all.
 */
function decide(request, url, sameOrigin) {
  if (request.method !== 'GET') return 'network-only';
  if (!sameOrigin) return 'network-only';
  if (request.mode === 'navigate' || request.destination === 'document') {
    return 'network-then-offline';
  }
  if (url.pathname === POLICY.offlineUrl) return 'cache-first';
  if (url.pathname === '/manifest.webmanifest') {
    return url.search ? 'network-only' : 'cache-first';
  }
  for (var i = 0; i < POLICY.cacheablePrefixes.length; i += 1) {
    if (url.pathname.indexOf(POLICY.cacheablePrefixes[i]) === 0) return 'cache-first';
  }
  return 'network-only';
}

self.addEventListener('fetch', function (event) {
  var request = event.request;
  var url;
  try {
    url = new URL(request.url);
  } catch (err) {
    return;
  }

  var sameOrigin = url.origin === self.location.origin;
  var decision = decide(request, url, sameOrigin);

  // Not respondWith at all: the request goes to the network exactly as it would
  // with no worker installed. This is the path every authenticated page takes.
  if (decision === 'network-only') return;

  if (decision === 'network-then-offline') {
    event.respondWith(
      fetch(request).catch(function () {
        return caches.match(POLICY.offlineUrl).then(function (cached) {
          return (
            cached ||
            new Response('Orbit is offline.', {
              status: 503,
              headers: { 'content-type': 'text/plain; charset=utf-8' },
            })
          );
        });
      })
    );
    return;
  }

  // cache-first, for content-hashed assets and the shell. A hit is served
  // without touching the network; a miss is fetched and kept, but only if it
  // actually succeeded — caching a 404 or a captive-portal redirect is how a
  // broken asset becomes permanent.
  event.respondWith(
    caches.match(request).then(function (cached) {
      if (cached) return cached;
      return fetch(request).then(function (response) {
        if (response && response.status === 200 && response.type === 'basic') {
          var copy = response.clone();
          caches.open(POLICY.version).then(function (cache) {
            cache.put(request, copy);
          });
        }
        return response;
      });
    })
  );
});
`;
}

export async function GET(): Promise<Response> {
  return new Response(source(), {
    headers: {
      'content-type': 'text/javascript; charset=utf-8',
      'service-worker-allowed': '/',
      'cache-control': 'no-store',
    },
  });
}
