import 'server-only';
import { asUser } from '@/lib/db';
import {
  hashInviteToken,
  type InviteRole,
  type InviteStatus,
  isInviteStatus,
} from '@/lib/invites';

/**
 * Invites and membership.
 *
 * Everything an *admin* does here goes through the ordinary policies on
 * `space_invites` and `space_members` — `app.is_space_admin` already says who
 * may do it, and none of it needed a new grant.
 *
 * Everything the *invitee* does goes through `app.space_invite()`, the one
 * SECURITY DEFINER function migration 0012 adds, because the person redeeming
 * an invitation is by definition not a member yet and no policy can be written
 * for "somebody who holds a secret". See the migration for the argument.
 */

export type InviteRow = {
  id: string;
  spaceId: string;
  role: string;
  invitedEmail: string | null;
  expiresAt: string;
  acceptedAt: string | null;
  acceptedByName: string | null;
  createdAt: string;
};

export async function listInvites(userId: string, spaceId: string): Promise<InviteRow[]> {
  return asUser(userId, async (tx) => {
    return tx<InviteRow[]>`
      select
        i.id,
        i.space_id                   as "spaceId",
        i.role::text                 as role,
        i.invited_email              as "invitedEmail",
        i.expires_at                 as "expiresAt",
        i.accepted_at                as "acceptedAt",
        p.display_name               as "acceptedByName",
        i.created_at                 as "createdAt"
      from public.space_invites i
      left join public.profiles p on p.id = i.accepted_by
      where i.space_id = ${spaceId}::uuid
      order by i.created_at desc
    `;
  });
}

export type MemberRow = {
  userId: string;
  displayName: string;
  email: string;
  role: string;
  status: string;
  joinedAt: string;
  isSpaceOwner: boolean;
};

/**
 * The roster, including people who have left.
 *
 * `status = 'left'` is what removal writes, so hiding those rows would hide the
 * fact that somebody was once here — which is the reason the status exists
 * rather than a delete.
 */
export async function listMembers(userId: string, spaceId: string): Promise<MemberRow[]> {
  return asUser(userId, async (tx) => {
    return tx<MemberRow[]>`
      select
        m.user_id            as "userId",
        p.display_name       as "displayName",
        p.email              as email,
        m.role::text         as role,
        m.status             as status,
        m.joined_at          as "joinedAt",
        (s.owner_id = m.user_id) as "isSpaceOwner"
      from public.space_members m
      join public.profiles p on p.id = m.user_id
      join public.spaces s on s.id = m.space_id
      where m.space_id = ${spaceId}::uuid
      order by (m.status = 'active') desc, p.display_name
    `;
  });
}

/**
 * Create an invitation and return the raw token *once*.
 *
 * The token is generated by the caller, hashed here, and only the hash is
 * written. Nothing in this file ever returns a raw token it read from the
 * database, because there is none to read.
 */
export async function createInvite(
  userId: string,
  spaceId: string,
  token: string,
  role: InviteRole,
  expiresAt: Date,
  invitedEmail: string | null,
): Promise<{ id: string } | { error: string }> {
  const rows = await asUser(userId, async (tx) => {
    return tx<{ id: string }[]>`
      insert into public.space_invites
        (space_id, owner_id, token_hash, role, invited_email, expires_at)
      values (
        ${spaceId}::uuid, ${userId}::uuid, ${hashInviteToken(token)},
        ${role}::app.member_role, ${invitedEmail}, ${expiresAt.toISOString()}
      )
      returning id
    `;
  });
  return rows[0] ?? { error: 'That invitation was not created.' };
}

/**
 * Revoke an unredeemed invitation by expiring it.
 *
 * `space_invites` has no `revoked_at` column and this work adds no migration,
 * so revoking is expiring: the token stops working immediately and the row
 * stays as the record of what was offered and to whom. Deleting it would erase
 * that, and an already-accepted invite is not revokable at all — the person is
 * in the space, and removing them is the other operation on this screen.
 */
export async function revokeInvite(
  userId: string,
  inviteId: string,
): Promise<{ ok: true } | { error: string }> {
  const rows = await asUser(userId, async (tx) => {
    return tx<{ id: string }[]>`
      update public.space_invites
      set expires_at = now()
      where id = ${inviteId}::uuid and accepted_at is null
      returning id
    `;
  });
  return rows[0]
    ? { ok: true }
    : {
        error:
          'That invitation could not be revoked: it has already been accepted, or it is not yours to revoke.',
      };
}

/**
 * Remove somebody from a space.
 *
 * `status = 'left'` rather than a delete: every policy checks `status =
 * 'active'`, so this takes effect immediately, and the row remains as the
 * record that they were here. The space's owner cannot be removed — ownership
 * is `spaces.owner_id` and a space with no owner is a space nobody can manage.
 */
export async function removeMember(
  userId: string,
  spaceId: string,
  memberId: string,
): Promise<{ ok: true } | { error: string }> {
  const rows = await asUser(userId, async (tx) => {
    return tx<{ user_id: string }[]>`
      update public.space_members m
      set status = 'left'
      where m.space_id = ${spaceId}::uuid
        and m.user_id = ${memberId}::uuid
        and m.status = 'active'
        and not exists (
          select 1 from public.spaces s
          where s.id = m.space_id and s.owner_id = m.user_id
        )
      returning m.user_id
    `;
  });
  return rows[0]
    ? { ok: true }
    : {
        error:
          'Nobody was removed. A space’s owner cannot be removed from it, and somebody who has already left cannot leave twice.',
      };
}

export type InviteView = {
  status: InviteStatus;
  inviteId: string | null;
  spaceId: string | null;
  spaceName: string | null;
  spaceColour: string | null;
  spaceIcon: string | null;
  spaceShortLabel: string | null;
  role: string | null;
  invitedEmail: string | null;
  expiresAt: string | null;
};

/**
 * Preview, accept or decline — one function, one set of checks.
 *
 * The raw token goes into Postgres as a bind parameter and is hashed there; it
 * is never compared in TypeScript, so there is no second opinion about what a
 * valid invitation is.
 */
async function invite(
  userId: string,
  token: string,
  action: 'preview' | 'accept' | 'decline',
): Promise<InviteView> {
  const rows = await asUser(userId, async (tx) => {
    return tx<
      {
        status: string;
        inviteId: string | null;
        spaceId: string | null;
        spaceName: string | null;
        spaceColour: string | null;
        spaceIcon: string | null;
        spaceShortLabel: string | null;
        role: string | null;
        invitedEmail: string | null;
        expiresAt: string | null;
      }[]
    >`
      select
        status,
        invite_id          as "inviteId",
        space_id           as "spaceId",
        space_name         as "spaceName",
        space_colour       as "spaceColour",
        space_icon         as "spaceIcon",
        space_short_label  as "spaceShortLabel",
        invite_role::text  as role,
        invited_email      as "invitedEmail",
        expires_at         as "expiresAt"
      from app.space_invite(${token}, ${action})
    `;
  });

  const row = rows[0];
  const status = row && isInviteStatus(row.status) ? row.status : 'unknown';
  return {
    status,
    inviteId: row?.inviteId ?? null,
    spaceId: row?.spaceId ?? null,
    spaceName: row?.spaceName ?? null,
    spaceColour: row?.spaceColour ?? null,
    spaceIcon: row?.spaceIcon ?? null,
    spaceShortLabel: row?.spaceShortLabel ?? null,
    role: row?.role ?? null,
    invitedEmail: row?.invitedEmail ?? null,
    expiresAt: row?.expiresAt ?? null,
  };
}

export const previewInvite = (userId: string, token: string) => invite(userId, token, 'preview');
export const acceptInvite = (userId: string, token: string) => invite(userId, token, 'accept');
export const declineInvite = (userId: string, token: string) => invite(userId, token, 'decline');
