import { Archive, ArrowLeft, Eye, Pencil } from 'lucide-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AsyncState } from '../components/AsyncState';
import { PageHeader } from '../components/AppShell';
import { SafeMarkdown } from '../components/SafeMarkdown';
import { getNote, linkNote, updateNote } from '../data/api';
import { queryKeys } from '../data/queryKeys';
import s from '../styles/ui.module.css';

export default function NoteDetailPage() {
  const { id = '' } = useParams(); const query = useQuery({ queryKey: queryKeys.note(id), queryFn: () => getNote(id), enabled: Boolean(id) }); const client = useQueryClient();
  const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [preview, setPreview] = useState(false); const [status, setStatus] = useState('Saved'); const [linkStatus, setLinkStatus] = useState(''); const hydrated = useRef('');
  useEffect(() => { if (query.data && hydrated.current !== query.data.id) { hydrated.current = query.data.id; setTitle(query.data.title); setBody(query.data.body_md); } }, [query.data]);
  useEffect(() => { if (!query.data || hydrated.current !== query.data.id || (title === query.data.title && body === query.data.body_md)) return; setStatus('Saving…'); const timer = window.setTimeout(() => { void updateNote(query.data!.id, { title, body_md: body }).then((note) => { client.setQueryData(queryKeys.note(note.id), note); void client.invalidateQueries({ queryKey: ['notes'] }); setStatus('Saved'); }).catch(() => setStatus('Save failed')); }, 700); return () => window.clearTimeout(timer); }, [title, body, query.data, client]);
  const note = query.data;
  return <><PageHeader title={note?.is_locked ? 'Locked note' : title || 'Untitled note'} subtitle={status} actions={<div className={s.toolbar}><button className={s.secondaryButton} onClick={() => setPreview((value) => !value)}>{preview ? <Pencil size={17} /> : <Eye size={17} />}{preview ? 'Edit' : 'Preview'}</button><button className={s.secondaryButton} onClick={() => note && void updateNote(note.id, { archived_at: new Date().toISOString() }).then(() => void client.invalidateQueries({ queryKey: ['notes'] }))}><Archive size={17} />Archive</button><Link className={s.secondaryButton} to="/notes"><ArrowLeft size={17} />Notes</Link></div>} /><AsyncState loading={query.isLoading} error={query.error} retry={() => void query.refetch()}>{note?.is_locked ? <section className={s.card}>This encrypted note is unavailable in this release.</section> : note && <section className={s.card}>{preview ? <SafeMarkdown source={body} /> : <div className={s.form}><div className={s.field}><label htmlFor="note-title">Title</label><input id="note-title" className={s.input} value={title} onChange={(event) => setTitle(event.target.value)} /></div><div className={s.field}><label htmlFor="note-body">Note</label><textarea id="note-body" className={s.textarea} style={{ minHeight: '55vh' }} value={body} onChange={(event) => setBody(event.target.value)} /></div><p className={status === 'Save failed' ? s.error : s.muted} role="status">{status}</p><form className={s.toolbar} onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setLinkStatus('Linking…'); try { await linkNote(note, String(data.get('kind')) as 'task' | 'person' | 'event' | 'place' | 'note', String(data.get('entity_id'))); setLinkStatus('Linked'); event.currentTarget.reset(); } catch (cause) { setLinkStatus(cause instanceof Error ? cause.message : 'Link failed'); } }}><span className={s.label}>Link note</span><select className={s.select} style={{ width: 'auto' }} name="kind"><option value="task">Task</option><option value="person">Person</option><option value="event">Event</option><option value="place">Place</option><option value="note">Note</option></select><input className={s.input} style={{ maxWidth: 360 }} name="entity_id" aria-label="Linked record ID" placeholder="Record ID" required /><button className={s.secondaryButton}>Link</button>{linkStatus && <span role="status">{linkStatus}</span>}</form></div>}</section>}</AsyncState></>;
}
