import { Copy, Link as LinkIcon, Plus, Save } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { AsyncState } from '../components/AsyncState';
import { PageHeader } from '../components/AppShell';
import { createInvite, createSpace, listMembers, renameSpace } from '../data/api';
import { useSpaces } from '../data/hooks';
import { queryKeys } from '../data/queryKeys';
import type { Member } from '../data/types';
import s from '../styles/ui.module.css';

export default function SpacePage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const spaces = useSpaces(); const auth = useAuth(); const client = useQueryClient(); const [invite, setInvite] = useState(''); const [message, setMessage] = useState('');
  const space = spaces.data?.find((item) => item.id === id); const members = useQuery({ queryKey: queryKeys.members(id), queryFn: () => listMembers(id), enabled: Boolean(id) });
  const create = useMutation({ mutationFn: (name: string) => createSpace(name), onSuccess: (spaceId) => { void client.invalidateQueries({ queryKey: queryKeys.spaces }); void navigate(`/spaces/${spaceId}`); } });
  if (!id) return <><PageHeader title="Spaces" subtitle="Spaces decide who can see household information." /><form className={`${s.card} ${s.form}`} onSubmit={(event) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('name')); create.mutate(name); }}><div className={s.field}><label htmlFor="space-name">New space name</label><input id="space-name" className={s.input} name="name" required /></div><button className={s.primaryButton}><Plus size={18} />Create space</button></form></>;
  return <><PageHeader title={space?.name ?? 'Space'} subtitle={space ? `${space.kind} · ${space.short_label}` : undefined} /><AsyncState loading={spaces.isLoading || members.isLoading} error={spaces.error || members.error}><div className={`${s.grid} ${s.todayGrid}`}><form className={`${s.card} ${s.form}`} onSubmit={async (event) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('name')); try { await renameSpace(id, name); await client.invalidateQueries({ queryKey: queryKeys.spaces }); setMessage('Saved'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Save failed'); } }}><h2>Space details</h2><div className={s.field}><label htmlFor="rename-space">Name</label><input id="rename-space" className={s.input} name="name" defaultValue={space?.name} /></div>{message && <p role="status">{message}</p>}<button className={s.primaryButton}><Save size={18} />Save</button></form><section className={`${s.card} ${s.cardFlush}`}><div className={s.cardHeader}><h2>Members</h2><span className={s.chip}>{members.data?.length ?? 0}</span></div><ul className={s.list}>{members.data?.map((member) => <li className={s.row} key={member.id}><div className={s.rowMain}><span className={s.rowTitle}>{member.profiles?.display_name ?? member.user_id}</span><span className={s.rowMeta}>{member.role === 'free_busy' ? 'Free/busy only — no titles or content' : member.role}</span></div></li>)}</ul></section></div><section className={s.card} style={{ marginTop: '1rem' }}><h2>Invitation link</h2><p className={s.muted}>The raw token appears once. Share it through a channel you trust.</p><form className={s.toolbar} onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!auth.user) return; try { const token = await createInvite(id, auth.user.id, String(data.get('role')) as Member['role'], String(data.get('email'))); setInvite(`${window.location.origin}/invite/${token}`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Invite failed'); } }}><select className={s.select} style={{ width: 'auto' }} name="role"><option value="member">Member</option><option value="viewer">Viewer</option><option value="free_busy">Free/busy only</option></select><input className={s.input} style={{ maxWidth: 300 }} type="email" name="email" placeholder="Optional email restriction" /><button className={s.primaryButton}><LinkIcon size={17} />Create link</button></form>{invite && <div className={s.quickAdd} style={{ marginTop: '1rem' }}><input className={s.input} readOnly value={invite} aria-label="Invitation link" /><button className={s.secondaryButton} onClick={() => void navigator.clipboard.writeText(invite)}><Copy size={17} />Copy</button></div>}</section></AsyncState></>;
}
