import { useQueryClient } from '@tanstack/react-query';
import { X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { createEvent, setEventRecurrence, updateEvent } from '../data/api';
import { useSpaces } from '../data/hooks';
import { supabase } from '../lib/supabase';
import type { Event } from '../data/types';
import s from '../styles/ui.module.css';

export default function CalendarEventEditor({ id, date, onClose }: { id: string | null; date: string; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [record, setRecord] = useState<Event | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const spaces = useSpaces(); const auth = useAuth(); const client = useQueryClient();
  useEffect(() => { dialog.current?.showModal(); if (id) void supabase.from('events').select('*, recurrence_rules:recurrence_rule_id(*)').eq('id', id).single().then(({ data, error: loadError }) => loadError ? setError(loadError.message) : setRecord(data as unknown as Event)); }, [id]);
  return <dialog ref={dialog} className={s.dialog} onClose={onClose} onCancel={onClose}><form onSubmit={async (event) => {
    event.preventDefault(); setSaving(true); setError(''); const data = new FormData(event.currentTarget); const starts = new Date(String(data.get('starts_at'))); const ends = new Date(String(data.get('ends_at')));
    try { const changes = { title: String(data.get('title')), body_md: String(data.get('body_md')), space_id: String(data.get('space_id')), starts_at: starts.toISOString(), ends_at: ends.toISOString(), all_day: data.get('all_day') === 'on' }; const saved = id ? await updateEvent(id, changes) : await createEvent({ ...changes, owner_id: auth.user!.id }); await setEventRecurrence(saved, String(data.get('rrule'))); await client.invalidateQueries({ queryKey: ['calendar'] }); onClose(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save event.'); } finally { setSaving(false); }
  }}><div className={`${s.dialogBody} ${s.form}`}><div className={s.pageHeader}><h2>{id ? 'Edit event' : 'New event'}</h2><button type="button" className={s.iconButton} onClick={onClose} aria-label="Close"><X size={18} /></button></div>{record?.is_locked ? <p className={s.error}>Locked events cannot be edited in this release.</p> : <><div className={s.field}><label htmlFor="event-title">Title</label><input id="event-title" className={s.input} name="title" defaultValue={record?.title ?? ''} required /></div><div className={s.field}><label htmlFor="event-space">Space</label><select id="event-space" className={s.select} name="space_id" defaultValue={record?.space_id ?? spaces.data?.[0]?.id}>{spaces.data?.map((space) => <option value={space.id} key={space.id}>{space.name}</option>)}</select></div><div className={s.toolbar}><div className={s.field}><label htmlFor="event-start">Starts</label><input id="event-start" className={s.input} name="starts_at" type="datetime-local" defaultValue={(record?.starts_at ?? `${date}T09:00`).slice(0, 16)} required /></div><div className={s.field}><label htmlFor="event-end">Ends</label><input id="event-end" className={s.input} name="ends_at" type="datetime-local" defaultValue={(record?.ends_at ?? `${date}T10:00`).slice(0, 16)} required /></div></div><label><input name="all_day" type="checkbox" defaultChecked={record?.all_day} /> All day</label><div className={s.field}><label htmlFor="event-repeat">Repeat</label><select id="event-repeat" className={s.select} name="rrule" defaultValue={record?.recurrence_rules?.rrule ?? ''}><option value="">Does not repeat</option><option value="FREQ=DAILY">Daily</option><option value="FREQ=WEEKLY">Weekly</option><option value="FREQ=MONTHLY">Monthly</option><option value="FREQ=YEARLY">Yearly</option></select></div><div className={s.field}><label htmlFor="event-notes">Notes</label><textarea id="event-notes" className={s.textarea} name="body_md" defaultValue={record?.body_md} /></div></>}{error && <div className={s.error}>{error}</div>}</div><div className={s.dialogActions}><button type="button" className={s.secondaryButton} onClick={onClose}>Cancel</button><button className={s.primaryButton} disabled={saving || record?.is_locked}>{saving ? 'Saving…' : 'Save event'}</button></div></form></dialog>;
}
